spring:
  datasource:
    url: jdbc:h2:mem:logdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

zookeeper:
  host: localhost:2181
  groupId: cityLog
logging:
  level:
    org:
     springframework:
      web: INFO
logging.file: cityLogs.log
